export interface TeamMember {
    name: string;
    role?: string;
  }
  
export const leadership: TeamMember[] = [
  { name: "Vanessa-Huynh", role: "President" },
  { name: "Jake-Poblete", role: "Internal VP" },
  { name: "Anna-Zhang", role: "External VP" },
  { name: "Anirudh-Krishna", role: "VP of Technology" },
  { name: "Veronica-Vasquez-Hernandez", role: "VP of Design" },
  { name: "Avni-Ghandi", role: "VP of Projects" },
  { name: "Sathya-Seelam", role: "Internal Executive" },
  { name: "Sarayu-Kocharlakota", role: "Internal Executive" },
  { name: "Erika-Wu", role: "Internal Executive" },
  { name: "Daniel-Gonzalez", role: "Project Lead" },
  { name: "Ayush-Manocha", role: "Project Lead" },
  { name: "Ananya-Kunjal", role: "Design Lead" },
  { name: "Sindhura-Appiah", role: "Design Lead" },
];

export const designers: TeamMember[] = [
  { name: "Audrey-Ostrom" },
  { name: "Angela-Chen" },
  { name: "Varia-Kniazhevich" },
  { name: "Alexis-Escuadro" },
  { name: "Hanne-Manning" },
  { name: "Ella-Blue-Wilmot" },
  { name: "Kaiwen-Tang" },
];

export const developers: TeamMember[] = [
  { name: "Vibha-Jallu" },
  { name: "Yohann-Moraes" },
  { name: "Sanjana-Manikandan" },
  { name: "Michelle-Wan" },
  { name: "Nick-Tran" },
  { name: "Nikolas-Peralta" },
  { name: "Adam-Carter" },
  { name: "Dhaathri-Vijay" },
  { name: "Brenda-Aceves" },
  { name: "Michael-Ramirez" },
  { name: "Malco-Salcedo" },
  { name: "Nathan-Dong" },
  { name: "Raghul-Madras" },
  { name: "Devarsh-Krishnan-Jayakrishnan" },
  { name: "Sam-Kumar" },
  { name: "Emely-Pineda" },
  { name: "Vishruth-Gudipati" },
];

export const alumni: TeamMember[] = [
  { name: "Neel-Walse", role: "VP of Design" },
  { name: "Harshita-Bhardwaj", role: "Co-President" },
  { name: "Nipun-Batra", role: "VP of Technology" },
  { name: "Crystal-Huang", role: "Co-President" },
  { name: "Shubham-Pruthi", role: "VP of Projects" },
  { name: "Fiona-Leung", role: "Internal VP" },
  { name: "Waylon-Williams", role: "Project Lead" },
  { name: "Vinoth-Gopikrishnan", role: "Project Lead" },
  { name: "Alexander-Sherbrooke", role: "Design Executive" },
  { name: "Ernest-So", role: "Designer" },
  { name: "Lemi-Hernandez", role: "Designer" },
  { name: "Anna-Lin", role: "Designer" },
  { name: "Akshay-Kamath", role: "Developer" },
  { name: "Andrew-Weckwerth", role: "Developer" },
  { name: "Anurag-Chillarige", role: "Developer" },
  { name: "Arveen-Azhand", role: "Developer" },
  { name: "Aviel-Hernandez", role: "Developer" },
  { name: "Emil-Wilson", role: "Developer" },
  { name: "Gandharva-Naveen", role: "Developer" },
  { name: "Haaris-Wasti", role: "Developer" },
  { name: "Lee-Way-Wang", role: "Developer" },
  { name: "Mukhul-Manicka", role: "Developer" },
  { name: "Nhi-Le", role: "Developer" },
  { name: "Jose-Chavez", role: "VP of Technology" },
  { name: "Irene-Wong", role: "Design Executive" },
  { name: "Alisha-Saboowala", role: "Co-President" },
  { name: "Arushi-Pandey", role: "VP of Projects" },
  { name: "Brent-Chen", role: "Project Lead" },
  { name: "Juhi-Malik", role: "VP of Operations" },
  { name: "Par-Dar", role: "Developer" },
  { name: "Aaron-Le", role: "Project Lead" },
  { name: "Akshitha-Nagaraj", role: "Developer" },
  { name: "Anthony-Furman", role: "Developer" },
  { name: "Benthan-Vu", role: "Developer" },
  { name: "Harsh-Dadhich", role: "Technology Executive" },
  { name: "Jamie-Quinn", role: "Developer" },
  { name: "Janesse-Liang", role: "Designer" },
  { name: "Jesse-de-Guzman", role: "Developer" },
  { name: "Jose-Patino", role: "Developer" },
  { name: "Lipitha-Tummala", role: "Developer" },
  { name: "Matthew-Kimotsuki", role: "Developer" },
  { name: "Michael-Takami", role: "Developer" },
  { name: "Neha-Suresh", role: "Designer" },
  { name: "Nicolas-Martinez", role: "Developer" },
  { name: "Reema-Cjintala", role: "Developer" },
  { name: "Rehan-Ali", role: "Developer" },
  { name: "Shreya-Hiremath", role: "Designer" },
  { name: "Sneha-Yalavarti", role: "Designer" },
  { name: "Stacy-Glushchenko", role: "Developer" },
  { name: "Yagnesh-V", role: "Developer" },
];